/* Automaticall generated by './build/build-entry.js' */

import Button from '../src/components/button'
import ButtonGroup from '../src/components/button-group'
import Col from '../src/components/col'
import Row from '../src/components/row'
import Tooltip from '../src/components/tooltip'
import Input from '../src/components/input'
import Form from '../src/components/form'
import FormItem from '../src/components/form-item'
import Tree from '../src/components/tree'
import Checkbox from '../src/components/checkbox'
import CheckboxGroup from '../src/components/checkbox-group'
import Radio from '../src/components/radio'
import RadioGroup from '../src/components/radio-group'

const components = [
  Button,
  ButtonGroup,
  Col,
  Row,
  Tooltip,
  Input,
  Form,
  FormItem,
  Tree,
  Checkbox,
  CheckboxGroup,
  Radio,
  RadioGroup
]

const install = function (Vue, opts = {}) {
  if (install.installed) return

  components.map(component => Vue.component(component.name, component))

  Vue.prototype.$GORGEOUS = {
    size: opts.size || '',
    zIndex: opts.zIndex || 100
  }
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '0.1.0',
  install,
  ...components
}
